In [29]:
import pandas
import pandas as pd

Series Creation

In [30]:
l=['red','green','blue','yellow']
pandas.Series(l, name='colours')

0       red
1     green
2      blue
3    yellow
Name: colours, dtype: str

In [31]:
s=pandas.Series(l, name='colours')#if u assign as s= then the output will be not shown it will be stored in s 

s[2] #used for indexing
#s[-2] #it doesnt support negative indexing

s[0]='brown' 
s 

s[5]='orange' #it is updating so it is mutable 
s

0     brown
1     green
2      blue
3    yellow
5    orange
Name: colours, dtype: str

In [32]:
s.drop(index=2) #drop method is used to remove the value

 #internally memory is not updated so again it will display the 4th index

0     brown
1     green
3    yellow
5    orange
Name: colours, dtype: str

DataFrame Creation

In [ ]:
d1={'name':['smith','blake','clark','smith','miller'],
     'sal':[2000,3000,1000,2000,1000],
     'comm':[None,None,100,None,500],
     'deptno':[10.0,20.0,10.0,10.0,30.0],
     'hiredate':['12/dec/2000','1/dec/2000','10/aug/2000','12/dec/2001','11/apr/2003']
     }
pandas.DataFrame(d1)

     name   sal   comm  deptno     hiredate
0   smith  2000    NaN    10.0  12/dec/2000
1   blake  3000    NaN    20.0   1/dec/2000
2   clark  1000  100.0    10.0  10/aug/2000
3   smith  2000    NaN    10.0  12/dec/2001
4  miller  1000  500.0    30.0  11/apr/2003

In [34]:
df1=pandas.DataFrame(d1)

In [35]:
d2={'name':['scott','martin','adams','martin','miller'],
     'sal':[3000,7000,1000,6000,5000],
     'comm':[None,None,100,None,500],
     'deptno':[10.0,30.0,30.0,20.0,30.0],
     'hiredate':['12/apr/2000','1/may/2000','10/aug/2002','12/dec/2002','11/apr/2002']
     }
pandas.DataFrame(d2)

     name   sal   comm  deptno     hiredate
0   scott  3000    NaN    10.0  12/apr/2000
1  martin  7000    NaN    30.0   1/may/2000
2   adams  1000  100.0    30.0  10/aug/2002
3  martin  6000    NaN    20.0  12/dec/2002
4  miller  5000  500.0    30.0  11/apr/2002

In [36]:
df2=pandas.DataFrame(d2)

In [37]:
df2

     name   sal   comm  deptno     hiredate
0   scott  3000    NaN    10.0  12/apr/2000
1  martin  7000    NaN    30.0   1/may/2000
2   adams  1000  100.0    30.0  10/aug/2002
3  martin  6000    NaN    20.0  12/dec/2002
4  miller  5000  500.0    30.0  11/apr/2002

In [40]:
pd.concat([df1,df2])
df=pd.concat([df1,df2],axis=0)

In [39]:
df3=pd.DataFrame({'column_x':[0]*10,
                  'column_y':[None]*10})

df3

   column_x column_y
0         0     None
1         0     None
2         0     None
3         0     None
4         0     None
5         0     None
6         0     None
7         0     None
8         0     None
9         0     None

In [41]:
pd.concat([df1,df2],axis=0) #axis=0
df=pd.concat([df1,df2],axis=0)
df

     name   sal   comm  deptno     hiredate
0   smith  2000    NaN    10.0  12/dec/2000
1   blake  3000    NaN    20.0   1/dec/2000
2   clark  1000  100.0    10.0  10/aug/2000
3   smith  2000    NaN    10.0  12/dec/2001
4  miller  1000  500.0    30.0  11/apr/2003
0   scott  3000    NaN    10.0  12/apr/2000
1  martin  7000    NaN    30.0   1/may/2000
2   adams  1000  100.0    30.0  10/aug/2002
3  martin  6000    NaN    20.0  12/dec/2002
4  miller  5000  500.0    30.0  11/apr/2002

In [42]:
df.reset_index()

   index    name   sal   comm  deptno     hiredate
0      0   smith  2000    NaN    10.0  12/dec/2000
1      1   blake  3000    NaN    20.0   1/dec/2000
2      2   clark  1000  100.0    10.0  10/aug/2000
3      3   smith  2000    NaN    10.0  12/dec/2001
4      4  miller  1000  500.0    30.0  11/apr/2003
5      0   scott  3000    NaN    10.0  12/apr/2000
6      1  martin  7000    NaN    30.0   1/may/2000
7      2   adams  1000  100.0    30.0  10/aug/2002
8      3  martin  6000    NaN    20.0  12/dec/2002
9      4  miller  5000  500.0    30.0  11/apr/2002

In [43]:
df.reset_index(drop=True) #gives new index

     name   sal   comm  deptno     hiredate
0   smith  2000    NaN    10.0  12/dec/2000
1   blake  3000    NaN    20.0   1/dec/2000
2   clark  1000  100.0    10.0  10/aug/2000
3   smith  2000    NaN    10.0  12/dec/2001
4  miller  1000  500.0    30.0  11/apr/2003
5   scott  3000    NaN    10.0  12/apr/2000
6  martin  7000    NaN    30.0   1/may/2000
7   adams  1000  100.0    30.0  10/aug/2002
8  martin  6000    NaN    20.0  12/dec/2002
9  miller  5000  500.0    30.0  11/apr/2002

In [44]:
df=df.reset_index(drop=True)

df

     name   sal   comm  deptno     hiredate
0   smith  2000    NaN    10.0  12/dec/2000
1   blake  3000    NaN    20.0   1/dec/2000
2   clark  1000  100.0    10.0  10/aug/2000
3   smith  2000    NaN    10.0  12/dec/2001
4  miller  1000  500.0    30.0  11/apr/2003
5   scott  3000    NaN    10.0  12/apr/2000
6  martin  7000    NaN    30.0   1/may/2000
7   adams  1000  100.0    30.0  10/aug/2002
8  martin  6000    NaN    20.0  12/dec/2002
9  miller  5000  500.0    30.0  11/apr/2002

In [45]:
pd.concat([df,df3],axis=0) #axis=0

     name     sal   comm  deptno     hiredate  column_x column_y
0   smith  2000.0    NaN    10.0  12/dec/2000       NaN      NaN
1   blake  3000.0    NaN    20.0   1/dec/2000       NaN      NaN
2   clark  1000.0  100.0    10.0  10/aug/2000       NaN      NaN
3   smith  2000.0    NaN    10.0  12/dec/2001       NaN      NaN
4  miller  1000.0  500.0    30.0  11/apr/2003       NaN      NaN
5   scott  3000.0    NaN    10.0  12/apr/2000       NaN      NaN
6  martin  7000.0    NaN    30.0   1/may/2000       NaN      NaN
7   adams  1000.0  100.0    30.0  10/aug/2002       NaN      NaN
8  martin  6000.0    NaN    20.0  12/dec/2002       NaN      NaN
9  miller  5000.0  500.0    30.0  11/apr/2002       NaN      NaN
0     NaN     NaN    NaN     NaN          NaN       0.0     None
1     NaN     NaN    NaN     NaN          NaN       0.0     None
2     NaN     NaN    NaN     NaN          NaN       0.0     None
3     NaN     NaN    NaN     NaN          NaN       0.0     None
4     NaN     NaN    NaN     NaN          NaN       0.0     None
5     NaN     NaN    NaN     NaN          NaN       0.0     None
6     NaN     NaN    NaN     NaN          NaN       0.0     None
7     NaN     NaN    NaN     NaN          NaN       0.0     None
8     NaN     NaN    NaN     NaN          NaN       0.0     None
9     NaN     NaN    NaN     NaN          NaN       0.0     None

In [ ]:
pd.concat([df,df3],axis=1) #axis=1

In [46]:
df

     name   sal   comm  deptno     hiredate
0   smith  2000    NaN    10.0  12/dec/2000
1   blake  3000    NaN    20.0   1/dec/2000
2   clark  1000  100.0    10.0  10/aug/2000
3   smith  2000    NaN    10.0  12/dec/2001
4  miller  1000  500.0    30.0  11/apr/2003
5   scott  3000    NaN    10.0  12/apr/2000
6  martin  7000    NaN    30.0   1/may/2000
7   adams  1000  100.0    30.0  10/aug/2002
8  martin  6000    NaN    20.0  12/dec/2002
9  miller  5000  500.0    30.0  11/apr/2002

In [47]:

df3

   column_x column_y
0         0     None
1         0     None
2         0     None
3         0     None
4         0     None
5         0     None
6         0     None
7         0     None
8         0     None
9         0     None

In [48]:
df=pd.concat([df,df3],axis=1) #axis=1

Head

In [49]:
df.head() #it will give first 5 elements for head|

     name   sal   comm  deptno     hiredate  column_x column_y
0   smith  2000    NaN    10.0  12/dec/2000         0     None
1   blake  3000    NaN    20.0   1/dec/2000         0     None
2   clark  1000  100.0    10.0  10/aug/2000         0     None
3   smith  2000    NaN    10.0  12/dec/2001         0     None
4  miller  1000  500.0    30.0  11/apr/2003         0     None

Tail

In [50]:
df.tail() #gives bottom 5 for tail(by default)

     name   sal   comm  deptno     hiredate  column_x column_y
5   scott  3000    NaN    10.0  12/apr/2000         0     None
6  martin  7000    NaN    30.0   1/may/2000         0     None
7   adams  1000  100.0    30.0  10/aug/2002         0     None
8  martin  6000    NaN    20.0  12/dec/2002         0     None
9  miller  5000  500.0    30.0  11/apr/2002         0     None

concat

In [67]:
pd.concat([df1,df2]) #axis=0
df=pd.concat([df1,df2],axis=0) #axis=0
df

     name   sal   comm  deptno     hiredate
0   smith  2000    NaN    10.0  12/dec/2000
1   blake  3000    NaN    20.0   1/dec/2000
2   clark  1000  100.0    10.0  10/aug/2000
3   smith  2000    NaN    10.0  12/dec/2001
4  miller  1000  500.0    30.0  11/apr/2003
0   scott  3000    NaN    10.0  12/apr/2000
1  martin  7000    NaN    30.0   1/may/2000
2   adams  1000  100.0    30.0  10/aug/2002
3  martin  6000    NaN    20.0  12/dec/2002
4  miller  5000  500.0    30.0  11/apr/2002

In [68]:
df=df.reset_index(drop=True)

In [69]:
df

     name   sal   comm  deptno     hiredate
0   smith  2000    NaN    10.0  12/dec/2000
1   blake  3000    NaN    20.0   1/dec/2000
2   clark  1000  100.0    10.0  10/aug/2000
3   smith  2000    NaN    10.0  12/dec/2001
4  miller  1000  500.0    30.0  11/apr/2003
5   scott  3000    NaN    10.0  12/apr/2000
6  martin  7000    NaN    30.0   1/may/2000
7   adams  1000  100.0    30.0  10/aug/2002
8  martin  6000    NaN    20.0  12/dec/2002
9  miller  5000  500.0    30.0  11/apr/2002

In [83]:
df3=pd.DataFrame({'column_x':[0]*10,
                  'column_y':[None]*10})

In [82]:
df3

   column_x column_y
0         0     None
1         0     None
2         0     None
3         0     None
4         0     None
5         0     None
6         0     None
7         0     None
8         0     None
9         0     None

In [84]:
df=pd.concat([df,df3],axis=1)

In [85]:
df

     name   sal   comm  deptno     hiredate  column_x column_y
0   smith  2000    NaN    10.0  12/dec/2000         0     None
1   blake  3000    NaN    20.0   1/dec/2000         0     None
2   clark  1000  100.0    10.0  10/aug/2000         0     None
3   smith  2000    NaN    10.0  12/dec/2001         0     None
4  miller  1000  500.0    30.0  11/apr/2003         0     None
5   scott  3000    NaN    10.0  12/apr/2000         0     None
6  martin  7000    NaN    30.0   1/may/2000         0     None
7   adams  1000  100.0    30.0  10/aug/2002         0     None
8  martin  6000    NaN    20.0  12/dec/2002         0     None
9  miller  5000  500.0    30.0  11/apr/2002         0     None

loc[ ]

In [74]:
df.loc[0]

name              smith
sal                2000
comm                NaN
deptno             10.0
hiredate    12/dec/2000
Name: 0, dtype: object

In [75]:
df.loc[[0,5,9]]

     name   sal   comm  deptno     hiredate
0   smith  2000    NaN    10.0  12/dec/2000
5   scott  3000    NaN    10.0  12/apr/2000
9  miller  5000  500.0    30.0  11/apr/2002

In [76]:
df.loc[df['sal']>2000]

     name   sal   comm  deptno     hiredate
1   blake  3000    NaN    20.0   1/dec/2000
5   scott  3000    NaN    10.0  12/apr/2000
6  martin  7000    NaN    30.0   1/may/2000
8  martin  6000    NaN    20.0  12/dec/2002
9  miller  5000  500.0    30.0  11/apr/2002

In [77]:
df.loc[df['sal']>2000,'name']

1     blake
5     scott
6    martin
8    martin
9    miller
Name: name, dtype: str

In [79]:
df.loc[df['sal']>2000,['name','deptno','comm']]

     name  deptno   comm
1   blake    20.0    NaN
5   scott    10.0    NaN
6  martin    30.0    NaN
8  martin    20.0    NaN
9  miller    30.0  500.0

In [80]:
df.loc[[5,7,0],'name']

5    scott
7    adams
0    smith
Name: name, dtype: str

info()

In [86]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10 non-null     str
 1   sal       10 non-null     int64
 2   comm      4 non-null      float64
 3   deptno    10 non-null     float64
 4   hiredate  10 non-null     str
 5   column_x  10 non-null     int64
 6   column_y  0 non-null      object
dtypes: float64(2), int64(2), object(1), str(2)
memory usage: 692.0+ bytes

In [ ]:
df

     name   sal   comm  deptno     hiredate  column_x column_y
0   smith  2000    NaN    10.0  12/dec/2000         0     None
1   blake  3000    NaN    20.0   1/dec/2000         0     None
2   clark  1000  100.0    10.0  10/aug/2000         0     None
3   smith  2000    NaN    10.0  12/dec/2001         0     None
4  miller  1000  500.0    30.0  11/apr/2003         0     None
5   scott  3000    NaN    10.0  12/apr/2000         0     None
6  martin  7000    NaN    30.0   1/may/2000         0     None
7   adams  1000  100.0    30.0  10/aug/2002         0     None
8  martin  6000    NaN    20.0  12/dec/2002         0     None
9  miller  5000  500.0    30.0  11/apr/2002         0     None