In [1]:
d={
    'Movie':['cocktail','mungarumale','tangerins','off campus','kgf'],
    'rating':[8,None,3,6,None],
    'language-year':['hindi-2012','kannada-2010','telgu-2011','tamil-2026','malyalam-2020'],
    'cast':[['katrina','salman'],['ananya','yash'],['sharukh','aliya'],['salman','aliya'],['kareena','sharukh']],
    'hotstar':[1,1,1,0,1],
    'netflix':['yes','no','yes','no','yes']
     }

dataframe as table
series as columns

In [2]:
import pandas as pd

In [3]:
df=pd.DataFrame(d)
df

         Movie  rating  language-year                cast  hotstar netflix
0     cocktail     8.0     hindi-2012   [katrina, salman]        1     yes
1  mungarumale     NaN   kannada-2010      [ananya, yash]        1      no
2    tangerins     3.0     telgu-2011    [sharukh, aliya]        1     yes
3   off campus     6.0     tamil-2026     [salman, aliya]        0      no
4          kgf     NaN  malyalam-2020  [kareena, sharukh]        1     yes

In [4]:
df.head() #starting 5datas it will display 
df.head(2) #if i need only 2 then i can put 2

         Movie  rating language-year               cast  hotstar netflix
0     cocktail     8.0    hindi-2012  [katrina, salman]        1     yes
1  mungarumale     NaN  kannada-2010     [ananya, yash]        1      no

In [5]:
df.tail(2) #if i need only 2 then i can put 2 it will display last 2 records since it is tail

        Movie  rating  language-year                cast  hotstar netflix
3  off campus     6.0     tamil-2026     [salman, aliya]        0      no
4         kgf     NaN  malyalam-2020  [kareena, sharukh]        1     yes

In [6]:
df.info() #gives summary of the columns reads the data

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Movie          5 non-null      str
 1   rating         3 non-null      float64
 2   language-year  5 non-null      str
 3   cast           5 non-null      object
 4   hotstar        5 non-null      int64
 5   netflix        5 non-null      str
dtypes: float64(1), int64(1), object(1), str(3)
memory usage: 481.0+ bytes

In [7]:
#dataframe_name[col_name] it is 1dimension 
df['Movie' ]
df[['Movie','rating']] #if i need to columns then 2 braces

         Movie  rating
0     cocktail     8.0
1  mungarumale     NaN
2    tangerins     3.0
3   off campus     6.0
4          kgf     NaN

In [8]:
df[df['Movie']=='tangerins'] #2dimension data

       Movie  rating language-year              cast  hotstar netflix
2  tangerins     3.0    telgu-2011  [sharukh, aliya]        1     yes

In [9]:
df['Movie'].str.title() #use str method title so the movie column become titlecase

0       Cocktail
1    Mungarumale
2      Tangerins
3     Off Campus
4            Kgf
Name: Movie, dtype: str

In [10]:
df['Movies']=df['Movie'].str.title()

In [11]:
df

,Movie,rating,language-year,cast,hotstar,netflix,Movies
0,cocktail,8.0,hindi-2012,"[katrina, salman]",1,yes,Cocktail
1,mungarumale,NaN,kannada-2010,"[ananya, yash]",1,no,Mungarumale
2,tangerins,3.0,telgu-2011,"[sharukh, aliya]",1,yes,Tangerins
3,off campus,6.0,tamil-2026,"[salman, aliya]",0,no,Off Campus
4,kgf,NaN,malyalam-2020,"[kareena, sharukh]",1,yes,Kgf

In [12]:
df.drop(columns=['Movie']) #drop is used to delete the particuler column and it is temporarily deleted

   rating  language-year                cast  hotstar netflix       Movies
0     8.0     hindi-2012   [katrina, salman]        1     yes     Cocktail
1     NaN   kannada-2010      [ananya, yash]        1      no  Mungarumale
2     3.0     telgu-2011    [sharukh, aliya]        1     yes    Tangerins
3     6.0     tamil-2026     [salman, aliya]        0      no   Off Campus
4     NaN  malyalam-2020  [kareena, sharukh]        1     yes          Kgf

In [13]:
df=df.drop(columns=['Movie']) #if u assign df= then it will be permenently delete

In [14]:
df #it will give u the data which is created after drop

   rating  language-year                cast  hotstar netflix       Movies
0     8.0     hindi-2012   [katrina, salman]        1     yes     Cocktail
1     NaN   kannada-2010      [ananya, yash]        1      no  Mungarumale
2     3.0     telgu-2011    [sharukh, aliya]        1     yes    Tangerins
3     6.0     tamil-2026     [salman, aliya]        0      no   Off Campus
4     NaN  malyalam-2020  [kareena, sharukh]        1     yes          Kgf

In [15]:
df.replace({'yes':1,'no':0})#replace method and use dictionary to pass multiple values

   rating  language-year                cast  hotstar netflix       Movies
0     8.0     hindi-2012   [katrina, salman]        1       1     Cocktail
1     NaN   kannada-2010      [ananya, yash]        1       0  Mungarumale
2     3.0     telgu-2011    [sharukh, aliya]        1       1    Tangerins
3     6.0     tamil-2026     [salman, aliya]        0       0   Off Campus
4     NaN  malyalam-2020  [kareena, sharukh]        1       1          Kgf

In [16]:
df=df.replace({'yes':1,'no':0})#replace method and use dictionary to pass multiple values and assign df =to delete permenently

In [17]:
df

   rating  language-year                cast  hotstar netflix       Movies
0     8.0     hindi-2012   [katrina, salman]        1       1     Cocktail
1     NaN   kannada-2010      [ananya, yash]        1       0  Mungarumale
2     3.0     telgu-2011    [sharukh, aliya]        1       1    Tangerins
3     6.0     tamil-2026     [salman, aliya]        0       0   Off Campus
4     NaN  malyalam-2020  [kareena, sharukh]        1       1          Kgf

In [18]:
df['language-year'].str.title()

0       Hindi-2012
1     Kannada-2010
2       Telgu-2011
3       Tamil-2026
4    Malyalam-2020
Name: language-year, dtype: str

In [19]:
df['language-year']=df['language-year'].str.title()

In [20]:
df

   rating  language-year                cast  hotstar netflix       Movies
0     8.0     Hindi-2012   [katrina, salman]        1       1     Cocktail
1     NaN   Kannada-2010      [ananya, yash]        1       0  Mungarumale
2     3.0     Telgu-2011    [sharukh, aliya]        1       1    Tangerins
3     6.0     Tamil-2026     [salman, aliya]        0       0   Off Campus
4     NaN  Malyalam-2020  [kareena, sharukh]        1       1          Kgf

In [21]:
df['language-year'].str.split('-') #split method should be used with hyphen

0       [Hindi, 2012]
1     [Kannada, 2010]
2       [Telgu, 2011]
3       [Tamil, 2026]
4    [Malyalam, 2020]
Name: language-year, dtype: object

In [22]:
df['language-year'].str.split('-',expand=True) #to make the method in structred format otr table format then use expand=true

          0     1
0     Hindi  2012
1   Kannada  2010
2     Telgu  2011
3     Tamil  2026
4  Malyalam  2020

In [23]:
df[['language','year']]=df['language-year'].str.split('-',expand=True) #permenently deleting and storing

In [24]:
df #now langauge and year are seperated

,rating,language-year,cast,hotstar,netflix,Movies,language,year
0,8.0,Hindi-2012,"[katrina, salman]",1,1,Cocktail,Hindi,2012
1,NaN,Kannada-2010,"[ananya, yash]",1,0,Mungarumale,Kannada,2010
2,3.0,Telgu-2011,"[sharukh, aliya]",1,1,Tangerins,Telgu,2011
3,6.0,Tamil-2026,"[salman, aliya]",0,0,Off Campus,Tamil,2026
4,NaN,Malyalam-2020,"[kareena, sharukh]",1,1,Kgf,Malyalam,2020

In [25]:
df.drop(columns=['language-year'])

   rating                cast  hotstar netflix       Movies  language  year
0     8.0   [katrina, salman]        1       1     Cocktail     Hindi  2012
1     NaN      [ananya, yash]        1       0  Mungarumale   Kannada  2010
2     3.0    [sharukh, aliya]        1       1    Tangerins     Telgu  2011
3     6.0     [salman, aliya]        0       0   Off Campus     Tamil  2026
4     NaN  [kareena, sharukh]        1       1          Kgf  Malyalam  2020

In [26]:
df=df.drop(columns=['language-year'])

In [27]:
df

   rating                cast  hotstar netflix       Movies  language  year
0     8.0   [katrina, salman]        1       1     Cocktail     Hindi  2012
1     NaN      [ananya, yash]        1       0  Mungarumale   Kannada  2010
2     3.0    [sharukh, aliya]        1       1    Tangerins     Telgu  2011
3     6.0     [salman, aliya]        0       0   Off Campus     Tamil  2026
4     NaN  [kareena, sharukh]        1       1          Kgf  Malyalam  2020

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rating    3 non-null      float64
 1   cast      5 non-null      object
 2   hotstar   5 non-null      int64
 3   netflix   5 non-null      object
 4   Movies    5 non-null      str
 5   language  5 non-null      str
 6   year      5 non-null      str
dtypes: float64(1), int64(1), object(2), str(3)
memory usage: 504.0+ bytes

In [29]:
df.astype({'year':'int'}) #year is in str datatype to convert it in to int use this method

   rating                cast  hotstar netflix       Movies  language  year
0     8.0   [katrina, salman]        1       1     Cocktail     Hindi  2012
1     NaN      [ananya, yash]        1       0  Mungarumale   Kannada  2010
2     3.0    [sharukh, aliya]        1       1    Tangerins     Telgu  2011
3     6.0     [salman, aliya]        0       0   Off Campus     Tamil  2026
4     NaN  [kareena, sharukh]        1       1          Kgf  Malyalam  2020

In [30]:
df=df.astype({'year':'int'})

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rating    3 non-null      float64
 1   cast      5 non-null      object
 2   hotstar   5 non-null      int64
 3   netflix   5 non-null      object
 4   Movies    5 non-null      str
 5   language  5 non-null      str
 6   year      5 non-null      int64
dtypes: float64(1), int64(2), object(2), str(2)
memory usage: 484.0+ bytes

loc[] for selecting rows and columns
loc[row_based,col_based] we need to pass this in loc and col based is optional
if i want to pass multile arg then use [] extara then it will take as row base 
ex: loc[[0,3,4]optional]

In [32]:
df.loc[2]

rating                   3.0
cast        [sharukh, aliya]
hotstar                    1
netflix                    1
Movies             Tangerins
language               Telgu
year                    2011
Name: 2, dtype: object

In [33]:
df.loc[[0,3,4]]

   rating                cast  hotstar netflix      Movies  language  year
0     8.0   [katrina, salman]        1       1    Cocktail     Hindi  2012
3     6.0     [salman, aliya]        0       0  Off Campus     Tamil  2026
4     NaN  [kareena, sharukh]        1       1         Kgf  Malyalam  2020

In [34]:
df.loc[[0,3,4]],['Movie']

(   rating                cast  hotstar netflix      Movies  language  year
 0     8.0   [katrina, salman]        1       1    Cocktail     Hindi  2012
 3     6.0     [salman, aliya]        0       0  Off Campus     Tamil  2026
 4     NaN  [kareena, sharukh]        1       1         Kgf  Malyalam  2020,
 ['Movie'])

In [35]:
df.loc[[0,3,4],['Movies','rating']]

       Movies  rating
0    Cocktail     8.0
3  Off Campus     6.0
4         Kgf     NaN

In [36]:
df['language']=='Hindi'

0     True
1    False
2    False
3    False
4    False
Name: language, dtype: bool

In [37]:
print(df['language']=='Hindi')

0     True
1    False
2    False
3    False
4    False
Name: language, dtype: bool

In [38]:
df['hotstar']==1

0     True
1     True
2     True
3    False
4     True
Name: hotstar, dtype: bool

In [39]:
df.loc[(df['language']=='Hindi') & (df['hotstar']==1)] #use bitwise and for comparing 2 values and both also should be true

   rating               cast  hotstar netflix    Movies language  year
0     8.0  [katrina, salman]        1       1  Cocktail    Hindi  2012

In [40]:
df.loc[(df['year']==2012)|(df['year']==2026)] #use bitwise or either of them should be true

   rating               cast  hotstar netflix      Movies language  year
0     8.0  [katrina, salman]        1       1    Cocktail    Hindi  2012
3     6.0    [salman, aliya]        0       0  Off Campus    Tamil  2026

In [41]:
df.fillna(2) #used to fill NAN values

   rating                cast  hotstar netflix       Movies  language  year
0     8.0   [katrina, salman]        1       1     Cocktail     Hindi  2012
1     2.0      [ananya, yash]        1       0  Mungarumale   Kannada  2010
2     3.0    [sharukh, aliya]        1       1    Tangerins     Telgu  2011
3     6.0     [salman, aliya]        0       0   Off Campus     Tamil  2026
4     2.0  [kareena, sharukh]        1       1          Kgf  Malyalam  2020

In [42]:
df

   rating                cast  hotstar netflix       Movies  language  year
0     8.0   [katrina, salman]        1       1     Cocktail     Hindi  2012
1     NaN      [ananya, yash]        1       0  Mungarumale   Kannada  2010
2     3.0    [sharukh, aliya]        1       1    Tangerins     Telgu  2011
3     6.0     [salman, aliya]        0       0   Off Campus     Tamil  2026
4     NaN  [kareena, sharukh]        1       1          Kgf  Malyalam  2020

In [43]:
df.to_csv('movies.csv')

In [44]:
df.to_csv('movies.csv',index=False)

In [45]:
df.to_excel('movies.xlsx')

In [46]:
df['cast'].astype(str) #cast was in obj converted into str by using this command

0     ['katrina', 'salman']
1        ['ananya', 'yash']
2      ['sharukh', 'aliya']
3       ['salman', 'aliya']
4    ['kareena', 'sharukh']
Name: cast, dtype: str

In [47]:
df['cast']=df['cast'].astype(str)

In [48]:
df

,rating,cast,hotstar,netflix,Movies,language,year
0,8.0,"['katrina', 'salman']",1,1,Cocktail,Hindi,2012
1,NaN,"['ananya', 'yash']",1,0,Mungarumale,Kannada,2010
2,3.0,"['sharukh', 'aliya']",1,1,Tangerins,Telgu,2011
3,6.0,"['salman', 'aliya']",0,0,Off Campus,Tamil,2026
4,NaN,"['kareena', 'sharukh']",1,1,Kgf,Malyalam,2020

In [49]:
df['cast'].str.strip('[]') #it removes [] braces

0     'katrina', 'salman'
1        'ananya', 'yash'
2      'sharukh', 'aliya'
3       'salman', 'aliya'
4    'kareena', 'sharukh'
Name: cast, dtype: str

In [50]:
df['cast']=df['cast'].str.strip('[]')

In [51]:
df['cast']

0     'katrina', 'salman'
1        'ananya', 'yash'
2      'sharukh', 'aliya'
3       'salman', 'aliya'
4    'kareena', 'sharukh'
Name: cast, dtype: str

In [52]:
df['cast'].str.replace("'","") #it will remove the inverted commas

0     katrina, salman
1        ananya, yash
2      sharukh, aliya
3       salman, aliya
4    kareena, sharukh
Name: cast, dtype: str

In [53]:
df['cast']=df['cast'].str.replace("'","")

In [54]:
df['cast']

0     katrina, salman
1        ananya, yash
2      sharukh, aliya
3       salman, aliya
4    kareena, sharukh
Name: cast, dtype: str

melt():is used to convert col to rows and we use when we want group or visualize
it has 3 parameters
pd.melt(df,id_vars,value_vars,vars_names,value_names)
id_vars=columns doesnt want to change
value_vars=columns to change rows 
var_names=columns name for (old columns)
value_names=columns name for values

In [55]:
pd.melt(df,value_vars=['hotstar','netflix'])

  variable value
0  hotstar     1
1  hotstar     1
2  hotstar     1
3  hotstar     0
4  hotstar     1
5  netflix     1
6  netflix     0
7  netflix     1
8  netflix     0
9  netflix     1

In [56]:
pd.melt(df,value_vars=['hotstar','netflix'],var_name='OTT')

       OTT value
0  hotstar     1
1  hotstar     1
2  hotstar     1
3  hotstar     0
4  hotstar     1
5  netflix     1
6  netflix     0
7  netflix     1
8  netflix     0
9  netflix     1

In [57]:
pd.melt(df,value_vars=['hotstar','netflix'],var_name='OTT',value_name='available')

       OTT available
0  hotstar         1
1  hotstar         1
2  hotstar         1
3  hotstar         0
4  hotstar         1
5  netflix         1
6  netflix         0
7  netflix         1
8  netflix         0
9  netflix         1

In [58]:
pd.melt(df,id_vars=['Movies','rating'],value_vars=['hotstar','netflix'],var_name='OTT',value_name='available')

        Movies  rating      OTT available
0     Cocktail     8.0  hotstar         1
1  Mungarumale     NaN  hotstar         1
2    Tangerins     3.0  hotstar         1
3   Off Campus     6.0  hotstar         0
4          Kgf     NaN  hotstar         1
5     Cocktail     8.0  netflix         1
6  Mungarumale     NaN  netflix         0
7    Tangerins     3.0  netflix         1
8   Off Campus     6.0  netflix         0
9          Kgf     NaN  netflix         1

In [59]:
df1=pd.melt(df,id_vars=['Movies','rating'],value_vars=['hotstar','netflix'],var_name='OTT',value_name='Available')

In [60]:
df1

        Movies  rating      OTT Available
0     Cocktail     8.0  hotstar         1
1  Mungarumale     NaN  hotstar         1
2    Tangerins     3.0  hotstar         1
3   Off Campus     6.0  hotstar         0
4          Kgf     NaN  hotstar         1
5     Cocktail     8.0  netflix         1
6  Mungarumale     NaN  netflix         0
7    Tangerins     3.0  netflix         1
8   Off Campus     6.0  netflix         0
9          Kgf     NaN  netflix         1

In [61]:
df1.drop(columns=['Available'])

        Movies  rating      OTT
0     Cocktail     8.0  hotstar
1  Mungarumale     NaN  hotstar
2    Tangerins     3.0  hotstar
3   Off Campus     6.0  hotstar
4          Kgf     NaN  hotstar
5     Cocktail     8.0  netflix
6  Mungarumale     NaN  netflix
7    Tangerins     3.0  netflix
8   Off Campus     6.0  netflix
9          Kgf     NaN  netflix

In [62]:
df1=df1.drop(columns=['Available'])

In [63]:
df1.reset_index(drop=True)

        Movies  rating      OTT
0     Cocktail     8.0  hotstar
1  Mungarumale     NaN  hotstar
2    Tangerins     3.0  hotstar
3   Off Campus     6.0  hotstar
4          Kgf     NaN  hotstar
5     Cocktail     8.0  netflix
6  Mungarumale     NaN  netflix
7    Tangerins     3.0  netflix
8   Off Campus     6.0  netflix
9          Kgf     NaN  netflix

In [64]:
df1=df1.reset_index(drop=True)

In [65]:
df1

        Movies  rating      OTT
0     Cocktail     8.0  hotstar
1  Mungarumale     NaN  hotstar
2    Tangerins     3.0  hotstar
3   Off Campus     6.0  hotstar
4          Kgf     NaN  hotstar
5     Cocktail     8.0  netflix
6  Mungarumale     NaN  netflix
7    Tangerins     3.0  netflix
8   Off Campus     6.0  netflix
9          Kgf     NaN  netflix

In [66]:
df['hotstar']+df['netflix'] #to check which movie is present in which platform

0    2
1    1
2    2
3    0
4    2
dtype: object

In [67]:
df['tot_plts']=df['hotstar']+df['netflix']

In [68]:
df

,rating,cast,hotstar,netflix,Movies,language,year,tot_plts
0,8.0,"katrina, salman",1,1,Cocktail,Hindi,2012,2
1,NaN,"ananya, yash",1,0,Mungarumale,Kannada,2010,1
2,3.0,"sharukh, aliya",1,1,Tangerins,Telgu,2011,2
3,6.0,"salman, aliya",0,0,Off Campus,Tamil,2026,0
4,NaN,"kareena, sharukh",1,1,Kgf,Malyalam,2020,2

In [69]:
df1

        Movies  rating      OTT
0     Cocktail     8.0  hotstar
1  Mungarumale     NaN  hotstar
2    Tangerins     3.0  hotstar
3   Off Campus     6.0  hotstar
4          Kgf     NaN  hotstar
5     Cocktail     8.0  netflix
6  Mungarumale     NaN  netflix
7    Tangerins     3.0  netflix
8   Off Campus     6.0  netflix
9          Kgf     NaN  netflix

### using aggregate functions(sum, min, max,count,mean)

In [70]:
df1['rating'].count() #using count

np.int64(6)

In [71]:
df1['rating'].agg(['min','max','mean','count']) #using all aggregate fn

min      3.000000
max      8.000000
mean     5.666667
count    6.000000
Name: rating, dtype: float64

In [72]:

df1.agg({'rating':'min','Movies':'count'})

rating     3.0
Movies    10.0
dtype: float64

In [73]:
df1.agg({'rating':['min','mean'],'Movies':'count'})

         rating  Movies
min    3.000000     NaN
mean   5.666667     NaN
count       NaN    10.0

### GroupBy

In [74]:
df1.groupby('OTT')

In [75]:
df1.groupby('OTT').agg({'rating':['max','mean'],'Movies':'count'})

        rating           Movies
           max      mean  count
OTT
hotstar    8.0  5.666667      5
netflix    8.0  5.666667      5